In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [5]:
w=torch.randn(2,3,requires_grad=True)#for a random number bw 1 and -1
b = torch.randn(2, requires_grad=True)
print(w)
print(b)


tensor([[ 0.3039,  1.4517, -0.3734],
        [ 0.8267,  0.5249,  0.3980]], requires_grad=True)
tensor([-1.1602, -0.0707], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t()+b

In [7]:
intital_preds=model(inputs)
print(intital_preds)

tensor([[102.2323, 112.5548],
        [130.3469, 146.8147],
        [198.1504, 165.2641],
        [ 78.4445, 121.5429],
        [133.0346, 135.2152]], grad_fn=<AddBackward0>)


In [8]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [10]:
loss=mse(intital_preds,targets)
print(loss)

tensor(2728.6694, grad_fn=<DivBackward0>)


In [11]:
loss.backward()

In [12]:
print(w)

tensor([[ 0.3039,  1.4517, -0.3734],
        [ 0.8267,  0.5249,  0.3980]], requires_grad=True)


In [13]:
print(w.grad)

tensor([[4516.2676, 4671.3369, 2785.5569],
        [3964.9688, 3279.6528, 2179.2937]])


In [14]:
step=1e-5


In [15]:
with torch.no_grad():
    w-=w.grad*step
    b-=b.grad*step
    w.grad.zero_()#this funciton is more imp if we are doing for >1 epocs
    b.grad.zero_()

In [16]:
preds=model(inputs)

In [17]:
loss=mse(preds,targets)
print(loss)

tensor(1988.8792, grad_fn=<DivBackward0>)


In [18]:
for i in range(100000):
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*step
        b-=b.grad*step
        w.grad.zero_()
        b.grad.zero_()

In [19]:
print(loss)

tensor(0.5026, grad_fn=<DivBackward0>)


In [20]:
print(w)

tensor([[-0.3913,  0.8479,  0.6950],
        [-0.3015,  0.7944,  0.9111]], requires_grad=True)
