In [1]:
import numpy as np
import torch 

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

In [5]:
w=torch.randn(2,3,requires_grad=True)#for a random number bw 1 and -1
b = torch.randn(2, requires_grad=True)
print(w)
print(b)


tensor([[ 0.7331, -2.3277,  0.5531],
        [ 0.2206, -0.2716,  0.2149]], requires_grad=True)
tensor([ 0.1615, -0.9790], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t()+b

In [7]:
intital_preds=model(inputs)
print(intital_preds)

tensor([[ -78.4936,    6.1703],
        [-102.5644,    8.9507],
        [-215.8882,   -5.7139],
        [  -4.6876,   17.7971],
        [-133.9958,    3.2136]], grad_fn=<AddBackward0>)


In [8]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [10]:
loss=mse(intital_preds,targets)
print(loss)

tensor(26637.7852, grad_fn=<DivBackward0>)


In [11]:
loss.backward()

In [12]:
print(w)

tensor([[ 0.7331, -2.3277,  0.5531],
        [ 0.2206, -0.2716,  0.2149]], requires_grad=True)


In [13]:
print(w.grad)

tensor([[-14946.5039, -18787.7852, -10906.4023],
        [ -7010.4238,  -8581.1611,  -5099.3584]])


In [14]:
step=1e-5


In [15]:
with torch.no_grad():
    w-=w.grad*step
    b-=b.grad*step
    w.grad.zero_()#this funciton is more imp if we are doing for >1 epocs
    b.grad.zero_()

In [16]:
preds=model(inputs)

In [17]:
loss=mse(preds,targets)
print(loss)

tensor(18948.6992, grad_fn=<DivBackward0>)


In [21]:
for i in range(100000000):
    preds=model(inputs)
    loss=mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*step
        b-=b.grad*step
        w.grad.zero_()
        b.grad.zero_()

KeyboardInterrupt: 

In [19]:
print(loss)

tensor(0.5022, grad_fn=<DivBackward0>)


In [20]:
print(w)

tensor([[-0.4013,  0.8481,  0.6866],
        [-0.2946,  0.7942,  0.9169]], requires_grad=True)
